name: tf2
channels:
  - defaults
dependencies:
  - python=3.6.10
  - six=1.15.0
  - numpy-base=1.19.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.4
  - pip:
    - keras-preprocessing==1.1.2
    - numpy==1.18.5
    - opencv-python==4.4.0.42
    - scipy==1.4.1
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow-estimator==2.3.0
    - tensorflow-gpu==2.3.0

